# Generated by Django 3.1.3 on 2020-12-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='confirm'),
        ),
        migrations.AlterField(
            model_name='comment_like',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', related_query_name='comment_like', to='blog.comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment_like',
            name='condition',
            field=models.BooleanField(verbose_name='Condition'),
        ),
    ]
