# Generated by Django 3.1.3 on 2020-12-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_setting_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', related_query_name='comment', to='blog.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='comment_like',
            name='condition',
            field=models.BooleanField(default=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', related_query_name='category', to='blog.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='post_setting',
            name='allow_discussion',
            field=models.BooleanField(default=True, verbose_name='Allow discussion'),
        ),
        migrations.AlterField(
            model_name='post_setting',
            name='author',
            field=models.BooleanField(default=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post_setting',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
    ]
