# Generated by Django 3.1.7 on 2021-02-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210222_0723'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
