# Generated by Django 3.1.4 on 2020-12-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket', related_query_name='basket', to='accounts.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Update at')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', related_query_name='order', to='accounts.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=16, verbose_name='amount')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', related_query_name='payment', to='orders.order', verbose_name='order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', related_query_name='payment', to='accounts.user', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Number of bought item')),
                ('price', models.IntegerField(verbose_name='Number of bought item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Order_Item', related_query_name='Order_Item', to='orders.order', verbose_name='order')),
                ('shop_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Order_Item', related_query_name='Order_Item', to='products.shopproduct', verbose_name='shop_product')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_item', related_query_name='basket_item', to='orders.basket', verbose_name='Basket')),
                ('shop_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_item', related_query_name='basket_item', to='products.shopproduct', verbose_name='User')),
            ],
            options={
                'verbose_name': 'BasketItem',
                'verbose_name_plural': 'BasketItems',
            },
        ),
    ]
