# Generated by Django 3.1.3 on 2020-12-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201202_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_setting',
            name='comment',
        ),
    ]
