# Generated by Django 3.1.3 on 2020-12-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_setting_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_setting',
            name='comment',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
