# Generated by Django 3.1.4 on 2021-02-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='products',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', related_query_name='product', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Discount_product', related_query_name='Discount_product', to='products.product', verbose_name='product'),
        ),
    ]
